context:
  name: surfa
  version: 0.6.3

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: ..

build:
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
      - ${{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
    - numpy >=2.0.0
  run:
    - scipy
    - numpy >=1.26.4
    - nibabel >= 2.1
    - pillow
    - python-xxhash

tests:
- python:
      imports:
        - surfa

about:
  homepage: https://github.com/freesurfer/surfa
  license: MIT
  description: Python utilities for medical image and surface-based analysis
  repository: https://github.com/freesurfer/surfa
  documentation: https://surfer.nmr.mgh.harvard.edu/docs/surfa/
